import type { NextPage } from 'next';
import Head from 'next/head';
import { Day as Date } from '../components/Day';

const Day: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Date />
      </main>
    </>
  );
};

export default Day;
