import type { NextPage } from 'next';
import Head from 'next/head';
import { Calendar } from '../components/Calendar';

const Month: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Calendar defaultView="month" />
      </main>
    </>
  );
};

export default Month;
