import { Button, Flex, Grid, GridItem, Stack } from '@chakra-ui/react';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useCalendar } from '../lib/useCalendar';
import { useYearMonthQuery } from '../lib/useYearMonthQuery';

const Month: NextPage = () => {
  const { year, month } = useYearMonthQuery();
  const { days, weekDays } = useCalendar(year, month);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Grid templateColumns="repeat(7, 1fr)" gap={1}>
          {weekDays.map((weekDay) => (
            <GridItem
              key={weekDay}
              w="7"
              h="7"
              display="flex"
              justifyContent="center"
              alignItems="center"
            >
              {weekDay}
            </GridItem>
          ))}
          {days.map((day, i) => (
            <GridItem
              key={i}
              w="7"
              h="7"
              display="flex"
              justifyContent="center"
              alignItems="center"
            >
              {day?.date()}
            </GridItem>
          ))}
        </Grid>
      </main>
    </>
  );
};

export default Month;
