import type { NextPage } from 'next';
import Head from 'next/head';
import { Flex, Grid, GridItem } from '@chakra-ui/react';
import { MiniCalendar } from '../components/Calendar';

const Year: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Flex w="full">
        <MiniCalendar year={2020} month={8} />
      </Flex>
    </>
  );
};

export default Year;
