import type { NextPage } from 'next';
import Head from 'next/head';
import { Flex, Grid, GridItem } from '@chakra-ui/react';
import { MiniCalendar } from '../components/Calendar';
import { MONTHS } from '../lib/constants';
import { useYearMonthQuery } from '../lib/useYearMonthQuery';

const Year: NextPage = () => {
  const { year } = useYearMonthQuery();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Flex w="full">
        {MONTHS.map((month) => (
          <MiniCalendar key={month} year={year} month={month} />
        ))}
      </Flex>
    </>
  );
};

export default Year;
