import type { GetServerSideProps, NextPage } from 'next';
import Head from 'next/head';
import { Day as Date } from '../../components/Day';
import { useCalendarRouter } from '../../shared/useCalendarRouter';

const Day: NextPage = () => {
  const { params } = useCalendarRouter();
  return (
    <>
      <Head>
        <title>
          {params.year}月{params.month}月{params.day}日
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Date {...params} />
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async () => {
  return { props: {} };
};

export default Day;
